// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import AddViewerReducer from "../add_viewer_reducer";
import CreateElementReducer from "../create_element_reducer";
import CreatePageReducer from "../create_page_reducer";
import CreateSectionReducer from "../create_section_reducer";
import CreateSiteReducer from "../create_site_reducer";
import CreateSiteWithContentReducer from "../create_site_with_content_reducer";
import DeleteElementReducer from "../delete_element_reducer";
import DeletePageReducer from "../delete_page_reducer";
import DeleteSectionReducer from "../delete_section_reducer";
import DeleteSiteReducer from "../delete_site_reducer";
import DeleteStyleReducer from "../delete_style_reducer";
import RemoveViewerReducer from "../remove_viewer_reducer";
import SetStyleReducer from "../set_style_reducer";
import ToggleChecklistReducer from "../toggle_checklist_reducer";
import UpdateElementReducer from "../update_element_reducer";
import UpdateElementContentReducer from "../update_element_content_reducer";
import UpdateElementVisibilityReducer from "../update_element_visibility_reducer";
import UpdatePageReducer from "../update_page_reducer";
import UpdateSectionReducer from "../update_section_reducer";
import UpdateSiteReducer from "../update_site_reducer";

export type AddViewerParams = __Infer<typeof AddViewerReducer>;
export type CreateElementParams = __Infer<typeof CreateElementReducer>;
export type CreatePageParams = __Infer<typeof CreatePageReducer>;
export type CreateSectionParams = __Infer<typeof CreateSectionReducer>;
export type CreateSiteParams = __Infer<typeof CreateSiteReducer>;
export type CreateSiteWithContentParams = __Infer<typeof CreateSiteWithContentReducer>;
export type DeleteElementParams = __Infer<typeof DeleteElementReducer>;
export type DeletePageParams = __Infer<typeof DeletePageReducer>;
export type DeleteSectionParams = __Infer<typeof DeleteSectionReducer>;
export type DeleteSiteParams = __Infer<typeof DeleteSiteReducer>;
export type DeleteStyleParams = __Infer<typeof DeleteStyleReducer>;
export type RemoveViewerParams = __Infer<typeof RemoveViewerReducer>;
export type SetStyleParams = __Infer<typeof SetStyleReducer>;
export type ToggleChecklistParams = __Infer<typeof ToggleChecklistReducer>;
export type UpdateElementParams = __Infer<typeof UpdateElementReducer>;
export type UpdateElementContentParams = __Infer<typeof UpdateElementContentReducer>;
export type UpdateElementVisibilityParams = __Infer<typeof UpdateElementVisibilityReducer>;
export type UpdatePageParams = __Infer<typeof UpdatePageReducer>;
export type UpdateSectionParams = __Infer<typeof UpdateSectionReducer>;
export type UpdateSiteParams = __Infer<typeof UpdateSiteReducer>;

