// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  sectionId: __t.u64().name("section_id"),
  sortOrder: __t.u32().name("sort_order"),
  name: __t.string(),
  elementType: __t.string().name("element_type"),
  content: __t.string(),
  attributes: __t.string(),
  visible: __t.bool(),
});
