// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const Admins = __t.object("Admins", {
  identity: __t.identity(),
  name: __t.string(),
  addedAt: __t.u64(),
});
export type Admins = __Infer<typeof Admins>;

export const ChatMessages = __t.object("ChatMessages", {
  id: __t.u64(),
  siteId: __t.u64(),
  role: __t.string(),
  content: __t.string(),
  metadata: __t.string(),
  status: __t.string(),
  createdAt: __t.u64(),
});
export type ChatMessages = __Infer<typeof ChatMessages>;

export const ChecklistState = __t.object("ChecklistState", {
  id: __t.u64(),
  siteSlug: __t.string(),
  itemId: __t.string(),
  checked: __t.bool(),
  checkedBy: __t.string(),
  updatedAt: __t.u64(),
});
export type ChecklistState = __Infer<typeof ChecklistState>;

export const EditingSections = __t.object("EditingSections", {
  id: __t.u64(),
  siteId: __t.u64(),
  sectionName: __t.string(),
  createdAt: __t.u64(),
});
export type EditingSections = __Infer<typeof EditingSections>;

export const Elements = __t.object("Elements", {
  id: __t.u64(),
  sectionId: __t.u64(),
  sortOrder: __t.u32(),
  name: __t.string(),
  elementType: __t.string(),
  content: __t.string(),
  attributes: __t.string(),
  visible: __t.bool(),
});
export type Elements = __Infer<typeof Elements>;

export const Pages = __t.object("Pages", {
  id: __t.u64(),
  siteId: __t.u64(),
  slug: __t.string(),
  title: __t.string(),
  sortOrder: __t.u32(),
});
export type Pages = __Infer<typeof Pages>;

export const PendingAdmins = __t.object("PendingAdmins", {
  id: __t.u64(),
  identityHex: __t.string(),
  name: __t.string(),
  requestedAt: __t.u64(),
});
export type PendingAdmins = __Infer<typeof PendingAdmins>;

export const Sections = __t.object("Sections", {
  id: __t.u64(),
  pageId: __t.u64(),
  sortOrder: __t.u32(),
  name: __t.string(),
  sectionType: __t.string(),
  background: __t.string(),
  cssClass: __t.string(),
  visible: __t.bool(),
});
export type Sections = __Infer<typeof Sections>;

export const Sites = __t.object("Sites", {
  id: __t.u64(),
  slug: __t.string(),
  title: __t.string(),
  description: __t.string(),
  createdAt: __t.u64(),
  updatedAt: __t.u64(),
});
export type Sites = __Infer<typeof Sites>;

export const Styles = __t.object("Styles", {
  id: __t.u64(),
  siteId: __t.u64(),
  property: __t.string(),
  value: __t.string(),
});
export type Styles = __Infer<typeof Styles>;

export const ViewerProfiles = __t.object("ViewerProfiles", {
  email: __t.string(),
  name: __t.string(),
  pictureUrl: __t.string(),
  updatedAt: __t.u64(),
});
export type ViewerProfiles = __Infer<typeof ViewerProfiles>;

export const Viewers = __t.object("Viewers", {
  email: __t.string(),
  addedAt: __t.u64(),
});
export type Viewers = __Infer<typeof Viewers>;

